### ISSUE TITLE
Fix icon spacing

### ISSUE THREAD

**Issue by gpspake** [uthsc/UTHSC#11]
Icon spacing is inconsistent in off canvas navigation. Button icons in main content need space between text. This can probably be merged in to master once it's fixed.

**Comment by ctbarber** [comment]
Two separate issues both can be seen on the internal template page

**Comment by nicwinn** [comment]
1. ![image](https://cloud.githubusercontent.com/assets/9751044/7738684/d18e4026-ff1c-11e4-90ab-52abcb0bbf02.png)
2. ![image](https://cloud.githubusercontent.com/assets/9751044/7738687/d98c8b20-ff1c-11e4-897e-2db7f9171002.png)
