### ISSUE TITLE
Need "go" button for Search bars

### ISSUE THREAD

**Issue by ctbarber** [uthsc/UTHSC#2]
Can be inside the search area if needed for space considerations.

**Comment by nicwinn** [comment]
1. ![image](https://cloud.githubusercontent.com/assets/9751044/7737521/670acf54-ff11-11e4-8917-ad1d5630246e.png)
2. ![image](https://cloud.githubusercontent.com/assets/9751044/7737532/78d80238-ff11-11e4-99da-64525738cee1.png)
3. ![image](https://cloud.githubusercontent.com/assets/9751044/7737548/8ea1f308-ff11-11e4-8591-f1a05d246c3d.png)
4. ![image](https://cloud.githubusercontent.com/assets/9751044/7737561/9fc9424e-ff11-11e4-8af1-f93ae95374a2.png)

**Comment by nicwinn** [comment]
removed space between search bar and close menu bar
![](https://cloud.githubusercontent.com/assets/9751044/7737561/9fc9424e-ff11-11e4-8af1-f93ae95374a2.png)
**now**
![image](https://cloud.githubusercontent.com/assets/9751044/7738175/4f00a766-ff17-11e4-88a1-32fd355993cb.png)
