### ISSUE TITLE
mission images to 500px and 100px high green bar with mission name

### ISSUE THREAD

**Issue by ctbarber** [uthsc/UTHSC#32]
All mission images should be 500px high
have 100px high green bar at the bottom of the image
the Mission Name (Education, Research, etc) should be in the green bar, justified with the left edge of the content

**Comment by nicwinn** [comment]
![image](https://cloud.githubusercontent.com/assets/9751044/7714897/5856daa8-fe48-11e4-8aaa-2aa5fa8d3932.png)
Also changed the h3 for news form "Education News" to News for Education"
