### ISSUE TITLE
"to top" link in magellan causes horizontal page scroll

### ISSUE THREAD

**Issue by ctbarber** [uthsc/UTHSC#33]

**Comment by ctbarber** [comment]
![image](https://cloud.githubusercontent.com/assets/2042232/7690388/cf32c89c-fd78-11e4-9c1e-f9d223a88ead.png)

**Comment by nicwinn** [comment]
![image](https://cloud.githubusercontent.com/assets/9751044/7713231/fe336548-fe3b-11e4-8874-f4c9ef1519c9.png)
