### ISSUE TITLE
Facebook section is hanging out in footer

### ISSUE THREAD

**Issue by ctbarber** [uthsc/UTHSC#35]
![image](https://cloud.githubusercontent.com/assets/2042232/7774867/016ddb78-0074-11e5-8938-a7c34d52a6fd.png)

**Comment by nicwinn** [comment]
I've tried adding `$(document).foundation('equalizer', 'reflow');` as prescribed on http://foundation.zurb.com/docs/components/equalizer.html#adding-new-content-after-page-load. I may be reading that wrong though. Any Ideas @gpspake on how to arrange the load order here.
