### ISSUE TITLE
Breadcrumbs in mobile

### ISSUE THREAD

**Issue by ctbarber** [uthsc/UTHSC#7]
In the stylesheet the following rule exists:

.offcanvas-nav.menu .uthsc-split-button-breadcrumb-links li:last-child a:before {
    content: "Current Page";
    font-weight: 700;
}

This causes the Current Page text to show, I think this would be better suited coming from the HTML. Therefore, I think the entire rule can be removed.

**Comment by nicwinn** [comment]
done
